import customtkinter as ctk


class App(ctk.CTk):
    """Generated by Visual Python IDE."""

    def __init__(self):
        super().__init__()
        ctk.set_appearance_mode("dark")
        self.title("My App")
        self.geometry("800x600")

        # [VP_REGION_CONFIG]
        self.ui_data = {
            "btn1": {
                "type": "CTkButton",
                "view": "Main",
                "x": 0.500,
                "y": 0.500,
                "w": 0.200,
                "h": 0.100,
                "text": "Click",
                "view": "Main",
            },
            "lbl1": {
                "type": "CTkLabel",
                "view": "Main",
                "x": 0.100,
                "y": 0.100,
                "w": 0.200,
                "h": 0.100,
                "text": "Hello",
                "view": "Main",
            },
            "btn2": {
                "type": "CTkButton",
                "view": "View_2",
                "x": 0.500,
                "y": 0.500,
                "w": 0.200,
                "h": 0.100,
                "text": "Go Back",
                "view": "View_2",
            },
        }
        # [VP_END_REGION]

        self._init_widgets()
        self._bind_events()

    def _init_widgets(self):
        """Create all widgets from ui_data."""
        self._widgets = {}
        for var_name, data in self.ui_data.items():
            wtype = data['type']
            x = data['x']
            y = data['y']
            w = data.get('w', 0.2)
            h = data.get('h', 0.06)
            widget = self._create_widget(wtype, data)
            if widget:
                self._widgets[var_name] = widget
                setattr(self, var_name, widget)
        self._navigate_to('Main')

    def _create_widget(self, wtype, data):
        """Factory method to create a widget by type."""
        if wtype == 'CTkLabel':
            return ctk.CTkLabel(self, text=data.get('text', 'Label'),
                text_color=data.get('text_color', '') or None,
                fg_color=data.get('fg_color', 'transparent'))
        elif wtype == 'CTkButton':
            return ctk.CTkButton(self, text=data.get('text', 'Button'),
                fg_color=data.get('fg_color', '') or None,
                hover_color=data.get('hover_color', '') or None,
                corner_radius=data.get('corner_radius', 8))
        elif wtype == 'CTkEntry':
            return ctk.CTkEntry(self,
                placeholder_text=data.get('placeholder', ''))
        elif wtype == 'CTkTextbox':
            tb = ctk.CTkTextbox(self)
            tb.insert('1.0', data.get('text', ''))
            return tb
        elif wtype == 'CTkComboBox':
            return ctk.CTkComboBox(self, values=data.get('values', ['Option 1']))
        elif wtype == 'CTkSlider':
            return ctk.CTkSlider(self, from_=data.get('from_', 0), to=data.get('to', 100))
        elif wtype == 'CTkSwitch':
            return ctk.CTkSwitch(self, text=data.get('text', 'Switch'))
        elif wtype == 'CTkCheckBox':
            return ctk.CTkCheckBox(self, text=data.get('text', 'Check'))
        elif wtype == 'CTkProgressBar':
            pb = ctk.CTkProgressBar(self)
            pb.set(data.get('value', 0.5))
            return pb
        return None

    def _bind_events(self):
        """Bind events from the node graph."""
        if hasattr(self, "btn1"):
            self.btn1.bind("<Button-1>", self._on_btn1_click_even)
        if hasattr(self, "btn2"):
            self.btn2.bind("<Button-1>", self._on_btn2_click_even)

    def _on_btn1_click_even(self, event=None):
        self._navigate_to("View_2")

    def _on_btn2_click_even(self, event=None):
        self._navigate_to("Main")

    def _navigate_to(self, view_name):
        for w in self._widgets.values():
            w.place_forget()
        for vn, data in self.ui_data.items():
            if data.get('view') == view_name:
                if vn in self._widgets:
                    wdata = self._widgets[vn]
                    wdata.place(relx=data['x'], rely=data['y'],
                                relwidth=data.get('w', 0.2), relheight=data.get('h', 0.06))


if __name__ == "__main__":
    app = App()
    app.mainloop()
