"""
code_parser.py — In-RAM bidirectional parser.
Reads ONLY the ui_data dict inside VP_REGION_CONFIG markers.
No heavy full-AST parsing — optimized for PC humilde.
"""
import ast
import re
from config import VP_REGION_START, VP_REGION_END


class CodeParser:
    """
    Lightweight parser that reads the ui_data dictionary from generated code.
    Only parses the text between [VP_REGION_CONFIG] and [VP_END_REGION],
    which is a simple dict literal — instant and safe.
    """

    def parse_ui_data(self, code: str) -> dict | None:
        """
        Extract the ui_data dict from code string (in RAM).
        Returns the dict, or None if the region is not found or invalid.
        """
        # Find region markers
        start_idx = code.find(VP_REGION_START)
        end_idx = code.find(VP_REGION_END)
        if start_idx == -1 or end_idx == -1 or end_idx <= start_idx:
            return None

        # Extract the code between markers
        region = code[start_idx + len(VP_REGION_START):end_idx].strip()

        # Find the dict assignment: self.ui_data = { ... }
        match = re.search(r'self\.ui_data\s*=\s*(\{.*\})', region, re.DOTALL)
        if not match:
            return None

        dict_str = match.group(1)

        # Parse just the dict literal using ast.literal_eval (safe, fast, in-RAM)
        try:
            ui_data = ast.literal_eval(dict_str)
            if isinstance(ui_data, dict):
                return ui_data
        except (ValueError, SyntaxError):
            return None

        return None

    def update_canvas_from_code(self, code: str, canvas_manager) -> bool:
        """
        Read ui_data from code and update the canvas state.
        Returns True if successful.
        """
        ui_data = self.parse_ui_data(code)
        if ui_data is None:
            return False

        # Group widgets by view
        views_data: dict[str, dict] = {}
        for var_name, wdata in ui_data.items():
            view_name = wdata.get("view", "Main")
            if view_name not in views_data:
                views_data[view_name] = {}
            views_data[view_name][var_name] = {
                "type": wdata.get("type", "CTkLabel"),
                "rx": wdata.get("x", 0.5),
                "ry": wdata.get("y", 0.5),
                "rw": wdata.get("w", 0.2),
                "rh": wdata.get("h", 0.06),
                "props": {k: v for k, v in wdata.items()
                          if k not in ("type", "view", "x", "y", "w", "h")},
            }

        # Merge into canvas manager
        for view_name, widgets in views_data.items():
            if view_name not in canvas_manager.views:
                canvas_manager.add_view(view_name)
            view = canvas_manager.views[view_name]
            view.widgets = widgets

        canvas_manager._render_view()
        return True

    def extract_user_code(self, code: str) -> str:
        """
        Extract the user's custom code (everything AFTER the class methods
        that are generated by the IDE). Looks for '# ─── Custom Code' marker.
        """
        marker = "# ─── Custom Code"
        idx = code.find(marker)
        if idx == -1:
            return ""
        # Get everything after the marker until the end of the class
        lines = code[idx + len(marker):].split("\n")
        # Remove common leading indentation
        result_lines = []
        for line in lines:
            if line.startswith("    "):
                result_lines.append(line[4:])
            else:
                result_lines.append(line)
        return "\n".join(result_lines).strip()

    def validate_syntax(self, code: str) -> tuple[bool, str]:
        """Check if the entire code block is syntactically valid Python."""
        try:
            ast.parse(code)
            return True, ""
        except SyntaxError as e:
            return False, f"Syntax Error at line {e.lineno}: {e.msg}"

    def validate_region(self, code: str) -> tuple[bool, str]:
        """
        Check if the VP_REGION_CONFIG is valid before refreshing.
        Returns (is_valid, error_message).
        """
        start_idx = code.find(VP_REGION_START)
        end_idx = code.find(VP_REGION_END)

        if start_idx == -1:
            return False, "Missing [VP_REGION_CONFIG] marker"
        if end_idx == -1:
            return False, "Missing [VP_END_REGION] marker"
        if end_idx <= start_idx:
            return False, "Region markers are in wrong order"

        region = code[start_idx + len(VP_REGION_START):end_idx].strip()
        match = re.search(r'self\.ui_data\s*=\s*(\{.*\})', region, re.DOTALL)
        if not match:
            return False, "Could not find self.ui_data = {...}"

        try:
            ast.literal_eval(match.group(1))
        except (ValueError, SyntaxError) as e:
            return False, f"Syntax error in ui_data: {e}"

        return True, ""
