"""
code_generator.py — Generates a clean Python class from canvas state.
Uses the VP_REGION_CONFIG dict pattern for ultra-fast bidirectional sync.
Output: single class App(ctk.CTk) with ui_data dict + event handlers.
"""
from config import VP_REGION_START, VP_REGION_END
import collections


class CodeGenerator:
    """Generates clean Python code from canvas + node state."""

    def __init__(self):
        self._indent = "    "

    def generate(self, canvas_data: dict, node_data: dict,
                 theme_mode: str = "dark", user_code: str = "") -> str:
        """
        Generate complete Python class from project state.
        `canvas_data` = CanvasManager.to_dict()
        `node_data` = NodeEngine.to_dict()
        `user_code` = user's custom functions from the IDE code editor
        """
        lines = []

        # ─── Imports ──────────────────────────────────────────────
        lines.append("import customtkinter as ctk")
        has_images = self._has_images(canvas_data)
        if has_images:
            lines.append("from PIL import Image")
        lines.append("")
        lines.append("")

        # ─── Class ────────────────────────────────────────────────
        lines.append("class App(ctk.CTk):")
        lines.append(f'{self._indent}"""Generated by Visual Python IDE."""')
        lines.append("")

        # __init__
        lines.append(f"{self._indent}def __init__(self):")
        lines.append(f"{self._indent}{self._indent}super().__init__()")
        lines.append(f"{self._indent}{self._indent}ctk.set_appearance_mode(\"{theme_mode}\")")

        # Window config
        lines.append(f'{self._indent}{self._indent}self.title("My App")')
        geom = canvas_data.get("project_geometry", "800x600")
        lines.append(f'{self._indent}{self._indent}self.geometry("{geom}")')
        lines.append("")

        # VP_REGION_CONFIG — the fast-parseable ui_data dict
        lines.append(f"{self._indent}{self._indent}{VP_REGION_START}")
        lines.append(f"{self._indent}{self._indent}self.ui_data = {{")
        lines.extend(self._generate_ui_data(canvas_data))
        lines.append(f"{self._indent}{self._indent}}}")
        lines.append(f"{self._indent}{self._indent}{VP_REGION_END}")
        lines.append("")

        lines.append(f"{self._indent}{self._indent}self._vars = {{}}")
        project_vars = canvas_data.get("project_variables", {})
        for k, v in project_vars.items():
            if str(v).lower() == "true":
                v_repr = "True"
            elif str(v).lower() == "false":
                v_repr = "False"
            else:
                try:
                    v_repr = float(v) if "." in str(v) else int(v)
                except ValueError:
                    v_repr = repr(v)
            lines.append(f"{self._indent}{self._indent}self._vars[{repr(k)}] = {v_repr}")

        lines.append(f"{self._indent}{self._indent}self._init_widgets()")
        lines.append(f"{self._indent}{self._indent}self._bind_events()")
        lines.append("")

        # _init_widgets
        first_view = next(iter(canvas_data.get("views", {})), "Main")
        lines.extend(self._generate_init_widgets(first_view))
        lines.append("")

        # _bind_events (from node graph)
        lines.extend(self._generate_event_bindings(node_data, canvas_data))
        lines.append("")

        # Event handler methods
        lines.extend(self._generate_event_handlers(node_data))

        # View management helper
        lines.extend(self._generate_navigation_helpers())

        # User custom code (Script nodes)
        if user_code.strip():
            lines.append("")
            lines.append(f"{self._indent}# ─── Custom Code ─────────────")
            for line in user_code.strip().split("\n"):
                lines.append(f"{self._indent}{line}")

        lines.append("")
        lines.append("")

        # ─── Main entry ──────────────────────────────────────────
        lines.append('if __name__ == "__main__":')
        lines.append(f"{self._indent}app = App()")
        lines.append(f"{self._indent}app.mainloop()")
        lines.append("")

        return "\n".join(lines)

    # ─── UI Data Dict ─────────────────────────────────────────────
    def _generate_ui_data(self, canvas_data: dict) -> list[str]:
        """Generate ui_data entries for all widgets across all views."""
        lines = []
        i2 = self._indent * 3
        i3 = self._indent * 4
        for view_name, view in canvas_data.get("views", {}).items():
            for var_name, wdata in view.get("widgets", {}).items():
                props_str = self._format_props(wdata)
                lines.append(f'{i2}"{var_name}": {{')
                lines.append(f'{i3}"type": "{wdata["type"]}",')
                lines.append(f'{i3}"view": "{view_name}",')
                lines.append(f'{i3}"x": {wdata["rx"]:.3f},')
                lines.append(f'{i3}"y": {wdata["ry"]:.3f},')
                lines.append(f'{i3}"w": {wdata["rw"]:.3f},')
                lines.append(f'{i3}"h": {wdata["rh"]:.3f},')
                for pk, pv in wdata.get("props", {}).items():
                    if isinstance(pv, str):
                        lines.append(f'{i3}"{pk}": "{pv}",')
                    elif isinstance(pv, list):
                        lines.append(f'{i3}"{pk}": {pv},')
                    else:
                        lines.append(f'{i3}"{pk}": {pv},')
                # Inject view bg_color
                if view.get("bg_color"):
                    lines.append(f'{i3}"bg_color": "{view["bg_color"]}",')
                lines.append(f'{i2}}},')
        return lines

    # ─── Widget Initialization ────────────────────────────────────
    def _generate_init_widgets(self, first_view: str) -> list[str]:
        i = self._indent
        lines = [
            f"{i}class _InitDynCtx(dict):",
            f"{i}{i}def __init__(self, app): self.app = app",
            f"{i}{i}def __missing__(self, k):",
            f"{i}{i}{i}w = getattr(self.app, k, None)",
            f"{i}{i}{i}if w and hasattr(w, 'get'): return str(w.get())",
            i + i + i + 'return str(self.app._vars.get(k, "{" + k + "}"))',
            "",
            f"{i}def _init_widgets(self):",
            f'{i}{i}"""Create all widgets from ui_data."""',
            f"{i}{i}self._widgets = {{}}",
            f"{i}{i}for var_name, data in self.ui_data.items():",
            f"{i}{i}{i}wtype = data['type']",
            f"{i}{i}{i}x = data['x']",
            f"{i}{i}{i}y = data['y']",
            f"{i}{i}{i}w = data.get('w', 0.2)",
            f"{i}{i}{i}h = data.get('h', 0.06)",
            f"{i}{i}{i}widget = self._create_widget(wtype, data)",
            f"{i}{i}{i}if widget:",
            f"{i}{i}{i}{i}self._widgets[var_name] = widget",
            f"{i}{i}{i}{i}setattr(self, var_name, widget)",
            f"{i}{i}self._navigate_to('{first_view}')",
            "",
            f"{i}def _create_widget(self, wtype, data):",
            f'{i}{i}"""Factory method to create a widget by type."""',
            f"{i}{i}t_text = str(data.get('text', ''))",
            f"{i}{i}t_place = str(data.get('placeholder', ''))",
            f"{i}{i}try: t_text = t_text.format_map(self._InitDynCtx(self))",
            f"{i}{i}except: pass",
            f"{i}{i}try: t_place = t_place.format_map(self._InitDynCtx(self))",
            f"{i}{i}except: pass",
            "",
            f"{i}{i}if wtype == 'CTkLabel':",
            f"{i}{i}{i}return ctk.CTkLabel(self, text=t_text or 'Label',",
            f"{i}{i}{i}    text_color=data.get('text_color', '') or None,",
            f"{i}{i}{i}    fg_color=data.get('fg_color', 'transparent'))",
            f"{i}{i}elif wtype == 'CTkButton':",
            f"{i}{i}{i}return ctk.CTkButton(self, text=t_text or 'Button',",
            f"{i}{i}{i}    fg_color=data.get('fg_color', '') or None,",
            f"{i}{i}{i}    hover_color=data.get('hover_color', '') or None,",
            f"{i}{i}{i}    corner_radius=data.get('corner_radius', 8))",
            f"{i}{i}elif wtype in ('CTkEntry', 'CTkEntryNum'):",
            f"{i}{i}{i}return ctk.CTkEntry(self,",
            f"{i}{i}{i}    placeholder_text=t_place)",
            f"{i}{i}elif wtype == 'CTkTextbox':",
            f"{i}{i}{i}tb = ctk.CTkTextbox(self)",
            f"{i}{i}{i}tb.insert('1.0', t_text)",
            f"{i}{i}{i}return tb",
            f"{i}{i}elif wtype == 'CTkComboBox':",
            f"{i}{i}{i}return ctk.CTkComboBox(self, values=data.get('values', ['Option 1']))",
            f"{i}{i}elif wtype == 'CTkSlider':",
            f"{i}{i}{i}return ctk.CTkSlider(self, from_=data.get('from_', 0), to=data.get('to', 100))",
            f"{i}{i}elif wtype == 'CTkSwitch':",
            f"{i}{i}{i}return ctk.CTkSwitch(self, text=t_text or 'Switch')",
            f"{i}{i}elif wtype == 'CTkCheckBox':",
            f"{i}{i}{i}return ctk.CTkCheckBox(self, text=t_text or 'Check')",
            f"{i}{i}elif wtype == 'CTkProgressBar':",
            f"{i}{i}{i}pb = ctk.CTkProgressBar(self)",
            f"{i}{i}{i}pb.set(data.get('value', 0.5))",
            f"{i}{i}{i}return pb",
            f"{i}{i}return None",
        ]
        return lines

    # ─── Event Bindings ───────────────────────────────────────────
    def _generate_event_bindings(self, node_data: dict,
                                  canvas_data: dict) -> list[str]:
        i = self._indent
        lines = [
            f"{i}def _bind_events(self):",
            f'{i}{i}"""Bind events from the node graph."""',
        ]
        event_nodes = [n for n in node_data.get("nodes", {}).values()
                       if n.get("node_type") == "event"]
        if not event_nodes:
            lines.append(f"{i}{i}pass")
            return lines

        trigger_map = {
            "Click": "<Button-1>",
            "Hover": "<Enter>",
            "FocusIn": "<FocusIn>",
            "FocusOut": "<FocusOut>",
            "KeyPress": "<Key>",
            "ValueChange": "<<Modified>>",
        }

        for enode in event_nodes:
            var = enode.get("var_name") or enode.get("params", {}).get("var_name", "")
            trigger = enode.get("params", {}).get("trigger", "Click")
            tk_event = trigger_map.get(trigger, "<Button-1>")
            handler_name = f"_on_{var}_{trigger.lower()}_{enode['id'][:4]}"
            if var:
                lines.append(
                    f'{i}{i}if hasattr(self, "{var}"):')
                lines.append(
                    f'{i}{i}{i}self.{var}.bind("{tk_event}", self.{handler_name})')
        return lines

    def _generate_event_handlers(self, node_data: dict) -> list[str]:
        """Generate handler methods for each event flow."""
        i = self._indent
        lines = []
        nodes = node_data.get("nodes", {})
        connections = node_data.get("connections", [])

        event_nodes = [n for n in nodes.values()
                       if n.get("node_type") == "event"]

        for enode in event_nodes:
            var = enode.get("var_name") or enode.get("params", {}).get("var_name", "")
            trigger = enode.get("params", {}).get("trigger", "Click")
            handler_name = f"_on_{var}_{trigger.lower()}_{enode['id'][:4]}"

            lines.append(f"{i}def {handler_name}(self, event=None):")

            # Follow connections to find actions
            visited = set([enode["id"]])
            action_lines = self._trace_flow(enode["id"], nodes, connections, visited, base_indent=2)
            if action_lines:
                lines.extend(action_lines)
            else:
                lines.append(f"{i}{i}pass")
            lines.append("")

        return lines

    def _trace_flow(self, current_id: str, nodes: dict, connections: list, visited: set, base_indent: int) -> list[str]:
        """DFS recursion handling decision trees with indentation limits."""
        # Hard limit to prevent insane indentation nesting depth bugs
        if base_indent > 20:
            return [f"{self._indent * base_indent}# Máxima profundidad de indentación alcanzada."]
            
        lines = []
        ind = self._indent * base_indent
        node = nodes.get(current_id, {})
        ntype = node.get("node_type", "")
        params = node.get("params", {})

        if ntype == "action":
            lines.extend(self._generate_action_code(node, ind))
            for conn in connections:
                if conn.get("from_node") == current_id:
                    to_id = conn.get("to_node")
                    if to_id not in visited:
                        visited.add(to_id)
                        lines.extend(self._trace_flow(to_id, nodes, connections, visited, base_indent))

        elif ntype == "decision":
            left = params.get("left_var", "")
            op = params.get("operator", "==")
            right = params.get("right_var", "")
            
            lines.append(f'{ind}def _eval_node_var(app_obj, val_str):')
            lines.append(f'{ind}{self._indent}if isinstance(val_str, str) and "{{" in val_str and "}}" in val_str:')
            lines.append(f'{ind}{self._indent}{self._indent}class _DCtx(dict):')
            lines.append(f'{ind}{self._indent}{self._indent}{self._indent}def __init__(self, a): self.a = a')
            lines.append(f'{ind}{self._indent}{self._indent}{self._indent}def __missing__(self, k):')
            lines.append(f'{ind}{self._indent}{self._indent}{self._indent}{self._indent}w = getattr(self.a, k, None)')
            lines.append(f'{ind}{self._indent}{self._indent}{self._indent}{self._indent}if w and hasattr(w, "get"): return str(w.get())')
            lines.append(ind + self._indent * 4 + 'return str(self.a._vars.get(k, "{" + k + "}"))')
            lines.append(f'{ind}{self._indent}{self._indent}try: return val_str.format_map(_DCtx(app_obj))')
            lines.append(f'{ind}{self._indent}{self._indent}except: pass')
            lines.append(f'{ind}{self._indent}w = getattr(app_obj, val_str, None)')
            lines.append(f'{ind}{self._indent}if w and hasattr(w, "get"): return str(w.get())')
            lines.append(f'{ind}{self._indent}return str(app_obj._vars.get(val_str, val_str))')
            
            lines.append(f'{ind}left_val = _eval_node_var(self, {repr(left)})')
            lines.append(f'{ind}right_val = _eval_node_var(self, {repr(right)})')
            
            # Use safe robust str cast string conversion as requested
            lines.append(f'{ind}if str(left_val) {op} str(right_val):')
            
            true_lines = []
            for conn in connections:
                if conn.get("from_node") == current_id and conn.get("from_port") == "true":
                    to_id = conn.get("to_node", "")
                    if to_id not in visited:
                        vp = set(visited); vp.add(to_id)
                        true_lines.extend(self._trace_flow(to_id, nodes, connections, vp, base_indent + 1))
            if true_lines: lines.extend(true_lines)
            else: lines.append(f'{ind}{self._indent}pass')
            
            lines.append(f'{ind}else:')
            false_lines = []
            for conn in connections:
                if conn.get("from_node") == current_id and conn.get("from_port") == "false":
                    to_id = conn.get("to_node", "")
                    if to_id not in visited:
                        vp = set(visited); vp.add(to_id)
                        false_lines.extend(self._trace_flow(to_id, nodes, connections, vp, base_indent + 1))
            if false_lines: lines.extend(false_lines)
            else: lines.append(f'{ind}{self._indent}pass')

        elif ntype == "event":
            for conn in connections:
                if conn.get("from_node") == current_id:
                    to_id = conn.get("to_node")
                    if to_id not in visited:
                        visited.add(to_id)
                        lines.extend(self._trace_flow(to_id, nodes, connections, visited, base_indent))

        return lines

    def _generate_action_code(self, node: dict, ind: str) -> list[str]:
        lines = []
        params = node.get("params", {})
        target = params.get("target", "")
        action = params.get("action", "")
        value = params.get("value", "")

        if action:
            if action == "change_view":
                view_name = params.get("view_name", "")
                lines.append(f'{ind}self._navigate_to("{view_name}")')
                
            elif action == "save_variable":
                source = params.get("source_entry", "")
                target_var = params.get("target_var", "my_var")
                if source and target_var:
                    lines.append(f'{ind}if hasattr(self, "{source}"):')
                    lines.append(f'{ind}{self._indent}self._vars["{target_var}"] = self.{source}.get()')
                    
            elif action == "print_variable":
                fmt = params.get("format_string", "")
                if target and fmt:
                    fmt_literal = repr(fmt)
                    lines.append(f'{ind}if hasattr(self, "{target}"):')
                    lines.append(f'{ind}{self._indent}# Concatenación {nombre_variable} soporta globales y values de entrys en vivo.')
                    lines.append(f'{ind}{self._indent}class _DynCtx(dict):')
                    lines.append(f'{ind}{self._indent}{self._indent}def __init__(self, app): self.app = app')
                    lines.append(f'{ind}{self._indent}{self._indent}def __missing__(self, k):')
                    lines.append(f'{ind}{self._indent}{self._indent}{self._indent}w = getattr(self.app, k, None)')
                    lines.append(f'{ind}{self._indent}{self._indent}{self._indent}if w and hasattr(w, "get"): return str(w.get())')
                    lines.append(ind + self._indent * 3 + 'return str(self.app._vars.get(k, "{" + k + "}"))')
                    lines.append(ind + self._indent + f'text = {fmt_literal}.format_map(_DynCtx(self))')
                    lines.append(f'{ind}{self._indent}self.{target}.configure(text=text)')

            elif target:
                if action == "change_text":
                    val_literal = repr(value)
                    lines.append(f'{ind}if hasattr(self, "{target}"):')
                    lines.append(f'{ind}{self._indent}class _DynCtx(dict):')
                    lines.append(f'{ind}{self._indent}{self._indent}def __init__(self, app): self.app = app')
                    lines.append(f'{ind}{self._indent}{self._indent}def __missing__(self, k):')
                    lines.append(f'{ind}{self._indent}{self._indent}{self._indent}w = getattr(self.app, k, None)')
                    lines.append(f'{ind}{self._indent}{self._indent}{self._indent}if w and hasattr(w, "get"): return str(w.get())')
                    lines.append(ind + self._indent * 3 + 'return str(self.app._vars.get(k, "{" + k + "}"))')
                    lines.append(ind + self._indent + f'text = {val_literal}.format_map(_DynCtx(self))')
                    lines.append(f'{ind}{self._indent}self.{target}.configure(text=text)')
                elif action == "change_color":
                    tc = params.get("text_color")
                    bg = params.get("fg_color")
                    lines.append(f'{ind}if hasattr(self, "{target}"):')
                    if tc:
                        lines.append(f'{ind}{self._indent}self.{target}.configure(text_color="{tc}")')
                    if bg:
                        lines.append(f'{ind}{self._indent}self.{target}.configure(fg_color="{bg}")')

        return lines

    def _generate_navigation_helpers(self) -> list[str]:
        i = self._indent
        return [
            f"{i}def _navigate_to(self, view_name):",
            f"{i}{i}for w in self._widgets.values():",
            f"{i}{i}{i}w.place_forget()",
            f"{i}{i}for vn, data in self.ui_data.items():",
            f"{i}{i}{i}if data.get('view') == view_name:",
            f"{i}{i}{i}{i}if vn in self._widgets:",
            f"{i}{i}{i}{i}{i}wdata = self._widgets[vn]",
            f"{i}{i}{i}{i}{i}wdata.place(relx=data['x'], rely=data['y'],",
            f"{i}{i}{i}{i}{i}            relwidth=data.get('w', 0.2), relheight=data.get('h', 0.06))",
            f"{i}{i}{i}{i}{i}wdata.lift()",
            "",
            f"{i}{i}# Set view background",
            f"{i}{i}vdata = next((v for v in self.ui_data.values() if v.get('view') == view_name), None)",
            f"{i}{i}if vdata and 'bg_color' in vdata:",
            f"{i}{i}{i}self.configure(fg_color=vdata['bg_color'])",
        ]

    # ─── Helpers ──────────────────────────────────────────────────
    def _has_images(self, canvas_data: dict) -> bool:
        for view in canvas_data.get("views", {}).values():
            for wdata in view.get("widgets", {}).values():
                if wdata.get("type") == "CTkImage":
                    return True
                if wdata.get("props", {}).get("image_path"):
                    return True
        return False

    def _format_props(self, wdata: dict) -> str:
        parts = []
        for k, v in wdata.get("props", {}).items():
            if isinstance(v, str):
                parts.append(f'"{k}": "{v}"')
            else:
                parts.append(f'"{k}": {v}')
        return ", ".join(parts)
